<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="9069" started-at="2017-09-01T20:26:33Z" finished-at="2017-09-01T20:26:42Z">
    <groups>
    </groups>
    <test name="testamazon" duration-ms="9069" started-at="2017-09-01T20:26:33Z" finished-at="2017-09-01T20:26:42Z">
      <class name="com.github.selenium.testamazon.tests.RegressionTests">
        <test-method status="PASS" signature="rampUp()[pri:0, instance:com.github.selenium.testamazon.tests.RegressionTests@1cd072a9]" name="rampUp" is-config="true" duration-ms="5697" started-at="2017-09-01T13:26:27Z" finished-at="2017-09-01T13:26:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rampUp -->
        <test-method status="FAIL" signature="testLoginPage()[pri:0, instance:com.github.selenium.testamazon.tests.RegressionTests@1cd072a9]" name="testLoginPage" duration-ms="7182" started-at="2017-09-01T13:26:33Z" finished-at="2017-09-01T13:26:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at com.github.selenium.testamazon.tests.RegressionTests.testLoginPage(RegressionTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginPage -->
        <test-method status="PASS" signature="testCreateWatchList()[pri:1, instance:com.github.selenium.testamazon.tests.RegressionTests@1cd072a9]" name="testCreateWatchList" duration-ms="1865" started-at="2017-09-01T13:26:40Z" finished-at="2017-09-01T13:26:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateWatchList -->
      </class> <!-- com.github.selenium.testamazon.tests.RegressionTests -->
    </test> <!-- testamazon -->
  </suite> <!-- Default Suite -->
</testng-results>
